CREATE TABLE dbo.UserLevel
	(
	UserLevelId INT IDENTITY NOT NULL,
	UserLevel VARCHAR(50) NOT NULL,
	Description VARCHAR(50) NULL,
	CreatedDate DATETIME DEFAULT (getdate()) NULL,
	DeletedDate DATETIME NULL,
	UpdatedDate DATETIME DEFAULT (getdate()) NULL,
	UpdatedBy INT NULL,
	CONSTRAINT PK__UserLeve__0C81DE8F7DCDAAA2 PRIMARY KEY (UserLevelId)
	)
GO

